In [1]:
#R matrices
#pulling our sequential numeric values
1:10


[1]  1  2  3  4  5  6  7  8  9 10

In [2]:
3:7

[1] 3 4 5 6 7

In [3]:
#assign sequential numeric range to a vector
v<- 1:10

In [4]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [5]:
#matrix() function
#note always does rows by columns!!
matrix(v)

[,1]
 [1,]  1  
 [2,]  2  
 [3,]  3  
 [4,]  4  
 [5,]  5  
 [6,]  6  
 [7,]  7  
 [8,]  8  
 [9,]  9  
[10,] 10

In [6]:
#argument nrow will reshape the matrix
matrix(v,nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [9]:
#byrow= changes the output number order to count sequential numbers in a row, lowest first
matrix(v,byrow=TRUE, nrow=2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [10]:
matrix(1:12,byrow=TRUE, nrow=4)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [11]:
lewiston<-c(12,14,18,13,17)
rockymount <-c(11,19,21,15,18)
whiteville<-c(14,17,23,11,9)

In [12]:
weights<-c(lewiston,rockymount,whiteville)

In [13]:
weights

[1] 12 14 18 13 17 11 19 21 15 18 14 17 23 11  9

In [14]:
weights.matrix<-matrix(weights,byrow=TRUE,nrow=3)
weights.matrix

[,1] [,2] [,3] [,4] [,5]
[1,] 12   14   18   13   17  
[2,] 11   19   21   15   18  
[3,] 14   17   23   11    9

In [15]:
#name rows = rownames()
#name columns = colnames()
days <-c('M','T','W','R','F')
loc.names<-c('lewiston','rockymount','whiteville')

In [16]:
days

[1] "M" "T" "W" "R" "F"

In [17]:
loc.names

[1] "lewiston"   "rockymount" "whiteville"

In [19]:
colnames(weights.matrix)<-days
rownames(weights.matrix)<-loc.names

In [20]:
weights.matrix

M  T  W  R  F 
lewiston   12 14 18 13 17
rockymount 11 19 21 15 18
whiteville 14 17 23 11  9

In [23]:
#a matrix with 5 rows and 10 columns
mat<-matrix(1:50,byrow=TRUE,nrow=5)
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [24]:
2*mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [25]:
mat/2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  0.5  1    1.5  2    2.5  3    3.5  4    4.5  5   
[2,]  5.5  6    6.5  7    7.5  8    8.5  9    9.5 10   
[3,] 10.5 11   11.5 12   12.5 13   13.5 14   14.5 15   
[4,] 15.5 16   16.5 17   17.5 18   18.5 19   19.5 20   
[5,] 20.5 21   21.5 22   22.5 23   23.5 24   24.5 25

In [26]:
2/mat

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] 2.00000000 1.00000000 0.66666667 0.50000000 0.40000000 0.33333333
[2,] 0.18181818 0.16666667 0.15384615 0.14285714 0.13333333 0.12500000
[3,] 0.09523810 0.09090909 0.08695652 0.08333333 0.08000000 0.07692308
[4,] 0.06451613 0.06250000 0.06060606 0.05882353 0.05714286 0.05555556
[5,] 0.04878049 0.04761905 0.04651163 0.04545455 0.04444444 0.04347826
     [,7]       [,8]       [,9]       [,10]     
[1,] 0.28571429 0.25000000 0.22222222 0.20000000
[2,] 0.11764706 0.11111111 0.10526316 0.10000000
[3,] 0.07407407 0.07142857 0.06896552 0.06666667
[4,] 0.05405405 0.05263158 0.05128205 0.05000000
[5,] 0.04255319 0.04166667 0.04081633 0.04000000

In [27]:
mat^2

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    1    4    9   16   25   36   49   64   81  100 
[2,]  121  144  169  196  225  256  289  324  361  400 
[3,]  441  484  529  576  625  676  729  784  841  900 
[4,]  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 
[5,] 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500

In [28]:
mat^0

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [29]:
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [30]:
#the comparison operators (==,!=,>,<,>=,<=)
mat>15

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
[1,] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[3,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[4,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[5,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [31]:
mat+mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  2    4    6    8   10   12   14   16   18    20  
[2,] 22   24   26   28   30   32   34   36   38    40  
[3,] 42   44   46   48   50   52   54   56   58    60  
[4,] 62   64   66   68   70   72   74   76   78    80  
[5,] 82   84   86   88   90   92   94   96   98   100

In [32]:
mat/mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    1    1    1    1    1    1    1    1    
[2,] 1    1    1    1    1    1    1    1    1    1    
[3,] 1    1    1    1    1    1    1    1    1    1    
[4,] 1    1    1    1    1    1    1    1    1    1    
[5,] 1    1    1    1    1    1    1    1    1    1

In [33]:
mat^mat

[,1]         [,2]         [,3]         [,4]         [,5]        
[1,] 1.000000e+00 4.000000e+00 2.700000e+01 2.560000e+02 3.125000e+03
[2,] 2.853117e+11 8.916100e+12 3.028751e+14 1.111201e+16 4.378939e+17
[3,] 5.842587e+27 3.414279e+29 2.088047e+31 1.333736e+33 8.881784e+34
[4,] 1.706917e+46 1.461502e+48 1.291100e+50 1.175664e+52 1.102507e+54
[5,] 1.330878e+66 1.501309e+68 1.734377e+70 2.050774e+72 2.480636e+74
     [,6]         [,7]         [,8]         [,9]         [,10]       
[1,] 4.665600e+04 8.235430e+05 1.677722e+07 3.874205e+08 1.000000e+10
[2,] 1.844674e+19 8.272403e+20 3.934641e+22 1.978420e+24 1.048576e+26
[3,] 6.156120e+36 4.434265e+38 3.314552e+40 2.567686e+42 2.058911e+44
[4,] 1.063874e+56 1.055513e+58 1.075912e+60 1.125951e+62 1.208926e+64
[5,] 3.068035e+76 3.877924e+78 5.007021e+80 6.600972e+82 8.881784e+84

In [34]:
mat2<-matrix(1:9,nrow=3)

In [35]:
mat2*mat2

[,1] [,2] [,3]
[1,] 1    16   49  
[2,] 4    25   64  
[3,] 9    36   81

In [36]:
#%*% this will follow linear algegra calculation as opposed to * which is element by element (1*1, 2*2...)
mat2 %*% mat2

[,1] [,2] [,3]
[1,] 30   66   102 
[2,] 36   81   126 
[3,] 42   96   150

In [40]:
#calculate across columns = use colSums()
colSums(weights.matrix)

M  T  W  R  F 
37 50 62 39 44

In [41]:
#calculate across rows = rowSums
rowSums(weights.matrix)

lewiston rockymount whiteville 
        74         84         74

In [42]:
colMeans(weights.matrix)

M        T        W        R        F 
12.33333 16.66667 20.66667 13.00000 14.66667

In [43]:
rowMeans(weights.matrix)

lewiston rockymount whiteville 
      14.8       16.8       14.8

In [45]:
#add the clayton location onto weights. matrix
clayton <- c(17,23,15,19,13)

In [46]:
#cbind binds a column together and rbind will bind a row together
#what are we appending it to (what is being appended), and the addition after the comma
ncsu.matrix<-rbind(weights.matrix,clayton)

In [47]:
ncsu.matrix

M  T  W  R  F 
lewiston   12 14 18 13 17
rockymount 11 19 21 15 18
whiteville 14 17 23 11  9
clayton    17 23 15 19 13

In [48]:
means.peanut <-rowMeans(ncsu.matrix)

In [49]:
means.peanut

lewiston rockymount whiteville    clayton 
      14.8       16.8       14.8       17.4

In [50]:
ncsu.matrix <-cbind(ncsu.matrix,means.peanut)

In [51]:
ncsu.matrix

M  T  W  R  F  means.peanut
lewiston   12 14 18 13 17 14.8        
rockymount 11 19 21 15 18 16.8        
whiteville 14 17 23 11  9 14.8        
clayton    17 23 15 19 13 17.4

In [52]:
short<-c(2,18,12)
long <-c(12,11,9,18,8)

In [54]:
cbind(ncsu.matrix,short)

Warning message in cbind(ncsu.matrix, short):
"number of rows of result is not a multiple of vector length (arg 2)"

M  T  W  R  F  means.peanut short
lewiston   12 14 18 13 17 14.8          2   
rockymount 11 19 21 15 18 16.8         18   
whiteville 14 17 23 11  9 14.8         12   
clayton    17 23 15 19 13 17.4          2

In [55]:
cbind(ncsu.matrix,long)

Warning message in cbind(ncsu.matrix, long):
"number of rows of result is not a multiple of vector length (arg 2)"

M  T  W  R  F  means.peanut long
lewiston   12 14 18 13 17 14.8         12  
rockymount 11 19 21 15 18 16.8         11  
whiteville 14 17 23 11  9 14.8          9  
clayton    17 23 15 19 13 17.4         18

In [56]:
#example.matrix[row][column] alternatively and perhaps preferably [example.matric[row,column]]
mat

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30   
[4,] 31   32   33   34   35   36   37   38   39   40   
[5,] 41   42   43   44   45   46   47   48   49   50

In [57]:
#will pull initial row and ignore the column
mat[1,]

[1]  1  2  3  4  5  6  7  8  9 10

In [58]:
mat[,1]

[1]  1 11 21 31 41

In [59]:
mat[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]  1    2    3    4    5    6    7    8    9   10   
[2,] 11   12   13   14   15   16   17   18   19   20   
[3,] 21   22   23   24   25   26   27   28   29   30

In [60]:
mat[3:5,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 21   22   23   24   25   26   27   28   29   30   
[2,] 31   32   33   34   35   36   37   38   39   40   
[3,] 41   42   43   44   45   46   47   48   49   50

In [61]:
mat[1:2,1:3]

[,1] [,2] [,3]
[1,]  1    2    3  
[2,] 11   12   13

In [62]:
mat[,9:10]

[,1] [,2]
[1,]  9   10  
[2,] 19   20  
[3,] 29   30  
[4,] 39   40  
[5,] 49   50

In [63]:
#if only want to grab numbers in a specific range
mat[2,5:6]

[1] 15 16

In [64]:
#factor and categorica matrices
#factor()

#example: P(peanut), M(maize), S(soybean), C (Cotton)
crop<-c('m','c','c','s','p','p','s','c','c','p','m','m','p','c','s')
id<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)

In [65]:
factor.crop<-factor(crop)

In [66]:
factor.crop

[1] m c c s p p s c c p m m p c s
Levels: c m p s

In [67]:
#nominal categorical variables there is no order to
#ordinal categorical variables there is an order to! like a subjective level 1-10
ord.cat<-c('cold','med','hot')

In [69]:
#ordered=TRUE
#levels = c(the order of levels)
temps<-c('cold', 'hot', 'hot','med', 'cold','med','hot','cold','med','med')
fact.temps <- factor(temps, ordered=TRUE, levels=c('cold','med','hot'))
#alt fact.temps <- factor(temps, ordered=TRUE, levels=ord.cat
fact.temps

[1] cold hot  hot  med  cold med  hot  cold med  med 
Levels: cold < med < hot

In [70]:
summary(temps)

   Length     Class      Mode 
       10 character character 

In [71]:
summary(fact.temps)

cold  med  hot 
   3    4    3