In [3]:
#install a library/module 
import numpy as np
#if say 'as np' it will call all numpy processes as np

In [4]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#arange()
#first value = 0; then up to but no includng last value therefore saying 10, it will include 9 but not 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#adding a third argument will create a stepwise (by whatever indicated value) arrangement
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
#zero() creates array of 0's
np.zeros(3)


array([0., 0., 0.])

In [13]:
#will create matrix of indicated rows,columns
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
#ones() - same as zeros
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((6,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
#range of evenly spaced values use linspace()
#total of 3 numbers spaced evenly from 0 to 10 -> notes this now include 10


np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
#identity matrix = eye(diagonal) where the diagonal defines how long

np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#np.random()
#.rand follows a uniform distribution
np.random.rand(2)

array([0.41401351, 0.51463372])

In [20]:
#makes a matrix by specifying rows and columns
np.random.rand(5,5)

array([[0.94208332, 0.83498625, 0.74747939, 0.76263718, 0.07675101],
       [0.04301255, 0.12300934, 0.02117992, 0.65550215, 0.55300492],
       [0.34942146, 0.56715646, 0.98210464, 0.2163843 , 0.08589232],
       [0.29554967, 0.55392409, 0.19745563, 0.74933938, 0.82153324],
       [0.80319902, 0.78653396, 0.64075193, 0.77937417, 0.80905416]])

In [21]:
#pulls from a standard/normal distribution uses randn(). thus it is centered at 0
np.random.randn(2)

array([0.53594768, 1.53839916])

In [22]:
np.random.randn(6,8)

array([[ 2.05900804,  0.71713831, -0.47743968,  0.84027287, -0.50777529,
        -1.2218355 ,  0.90189791, -0.36962753],
       [-0.35498907, -2.40979991, -1.62601061,  0.70285372, -1.37277416,
        -1.44013036,  1.10993688, -0.25273284],
       [ 0.21362904,  0.60670872,  1.15307404,  0.08006843,  1.2420391 ,
         0.20863117,  1.29798412, -0.54648247],
       [ 0.6583061 , -1.2835688 ,  0.55333858, -3.35721889, -2.04238403,
         0.48931386,  0.26011212, -1.87570138],
       [ 1.07208418, -0.77707384, -0.10309713, -0.94681893, -1.00419709,
        -1.53874315,  0.60716408, -1.35014765],
       [-0.13038866, -0.69922166,  2.10938953,  1.08050005, -0.0275251 ,
        -0.79047959, -1.19993405, -0.69168473]])

In [24]:
#random intergers from Low (inclusive) to high (exclusive) range
np.random.randint(1,100,10)

array([ 3, 63, 25, 49, 88, 35, 16, 33, 95, 47])

In [33]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr

array([30,  8, 32, 10, 17, 42, 13,  3, 19, 22])

In [36]:
#reshape to different matrix size or dimensions
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

42

In [38]:
#argmax pinpointing a ninex where the maxiumum exists -> 42 exists at the 5th location
ranarr.argmax()

5

In [39]:
ranarr.min()

3

In [40]:
ranarr.argmin()

7

In [41]:
arr.shape

(25,)

In [42]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(1,25).shape

(1, 25)

In [45]:
arr.reshape(25,1).shape

(25, 1)

In [47]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr=np.arange(25).reshape(5,5)

In [50]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
np.mat(arr)

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [52]:
#not a method, just an attribute therefore () is not needed at end
arr.dtype

dtype('int32')

In [53]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr=np.arange(25)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
#grab  the 9th element 9-1=8
arr[8]

8

In [57]:
arr[1:5]

array([1, 2, 3, 4])

In [59]:
#broadcasting which physically changes the indicated positions
arr[0:4] =100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [61]:
arr[3:7]==100

array([ True, False, False, False])

In [62]:
arr=np.arange(25)

In [63]:
slice_arr=arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [64]:
slice_arr[:]=99

In [65]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [66]:
#note that the original array is changed as well
#this avoids memory problems 
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
arr_copy=arr[0:6].copy()

In [69]:
arr_copy

array([99, 99, 99, 99, 99, 99])

In [72]:
arr_copy[:]=2

In [73]:
arr_copy

array([2, 2, 2, 2, 2, 2])

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [75]:
arr2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [76]:
np.arange(5,46,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [77]:
np.arange(5,46,5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr2d[1]

array([20, 25, 30])

In [79]:
arr2d[0]

array([ 5, 10, 15])

In [80]:
#array[row,column]; array[row][column]
#pulls out second row and first column
arr2d[1][0]

20

In [81]:
arr2d[1,0]

20

In [82]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [83]:
#takes out everything out up to but not including the 3rd row (labeled as 2) meaning rows 0 and 1
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
arr2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [85]:
arr2d[:,2]

array([15, 30, 45])

In [86]:
#grab columns and rows out of order = fantsy indexing
arr2d=np.arange(1,101).reshape(10,10)

In [87]:
arr2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [88]:
#grabs indicated rows
arr2d[[0,2,4,6,9]]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [89]:
#can also grab out of order
arr2d[[9,4,6,2]]

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30]])

In [90]:
#also applys to columns
arr2d[:,[4,7,1,3]]

array([[ 5,  8,  2,  4],
       [15, 18, 12, 14],
       [25, 28, 22, 24],
       [35, 38, 32, 34],
       [45, 48, 42, 44],
       [55, 58, 52, 54],
       [65, 68, 62, 64],
       [75, 78, 72, 74],
       [85, 88, 82, 84],
       [95, 98, 92, 94]])

In [91]:
arr2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [92]:
#grab along diagonal
#grabs elements 0,0; 1,1; 2,2 etc..
arr2d[[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]]

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [93]:
arr2d>30

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [94]:
arr2d*arr2d

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [97]:
A=np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [98]:
A*A

array([[ 1,  4],
       [ 9, 16]])

In [99]:
a = np.mat(A)

In [100]:
#linear calculation instead of element by element
a*a

matrix([[ 7, 10],
        [15, 22]])

In [101]:
#transpose
a.T

matrix([[1, 3],
        [2, 4]])

In [102]:
#inverse
a.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])